; PlatformIO Project Configuration File
; https://docs.platformio.org/page/projectconf.html

[env:ATmega328P]
platform = atmelavr
framework = arduino
board = ATmega328P
monitor_speed = 9600
; this is leftover from testing PlatformIO setup; probably not needed
build_flags = -D LED_BUILTIN=1
